modLoader = "javafml"
loaderVersion = "${forge_version_range}"
issueTrackerURL = "${issue_tracker}"
license = "${mod_license}"

[[mods]]
modId = "vstuff"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${homepage}"
authors = "${mod_authors}"
description = '''${mod_description}'''
logoFile = "icon.png"

[[dependencies.vstuff]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.vstuff]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vstuff]]
    modId="valkyrienskies"
    mandatory=true
    versionRange="[${vs2_min_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.vstuff]]
    modId="create"
    mandatory=true
    versionRange="[${create_major_version},)"
    ordering="AFTER"
    side="BOTH"