name: Compile and Upload Mod to Testers Channel

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: Send Mod to Discord
      uses: bytelabs-software/discord-commit-notifications@v1
      with:
         webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
         file-path: './build/reobfJar/output.jar'
         embed-title: 'New Vstuff Test Build'
         embed-color: '0x00ff00'
